PRJ = LavaStream

EXEC = LavaStream.so
SUBPRO=disco wxqDocView LavaBase

CPP_INCLUDES = -I. -I../wxqDocView -I../LavaBase -I../disco

CPP_FLAGS = -DLAVASTREAM_EXPORT

include ../common.mk

DLL = LAVASTREAM
		
