PRJ = LavaStream

EXEC = LavaStream.so
SUBPRO=SFLsockets disco wxqDocView LavaBase

CPP_INCLUDES = -I. -I../wxqDocView -I../LavaBase -I../disco -I$(QTDIR)/include

include ../common.mk

DLL = LAVASTREAM
		
