QMAKE_OBJCXXFLAGS_PRECOMPILE =
SOURCES = $$system(ls *.cpp)
SOURCES -= Precompiler_all.cpp
HEADERS = $$system(ls *.h)
HEADERS -= Precompiler_all.h
QT += core network
INCLUDEPATH = ../disco
DESTDIR = ../../bin
macx:QMAKE_LFLAGS += -F../../lib
else:QMAKE_LFLAGS += -L../../lib -Wl,-rpath,../lib
macx:LIBS += -framework disco
else:LIBS += -ldisco
CONFIG += warn_off qt qtestlib
TARGET = LPC
PRECOMPILED_HEADER = Precompiler_all.h
