#ifndef _LavaPE_UI_PCH
#define _LavaPE_UI_PCH

#include "disco_all.h"
#include "wxqDocView_all.h"
#include "LavaBase_all.h"

#include "LavaPEMainFrameBase.h"
#include "ui_cmainframe.h"
#include "ui_idd_attrbox.h"
#include "ui_idd_chainformpage.h"
#include "ui_idd_compspecbox.h"
#include "ui_idd_corroverbox.h"
#include "ui_idd_enumbox.h"
#include "ui_idd_enumitem.h"
#include "ui_idd_findbynamebox.h"
#include "ui_idd_findrefsbox.h"
#include "ui_idd_fontcolorpage.h"
#include "ui_idd_formbox.h"
#include "ui_idd_formview.h"
#include "ui_idd_ftextpage.h"
#include "ui_idd_funcbox.h"
#include "ui_idd_generalpage.h"
#include "ui_idd_gotodeclsel.h"
#include "ui_idd_implbox.h"
#include "ui_idd_includebox.h"
#include "ui_idd_initbox.h"
#include "ui_idd_interfacebox.h"
#include "ui_idd_iobox.h"
#include "ui_idd_iopage.h"
#include "ui_idd_literalitem.h"
#include "ui_idd_literalspage.h"
#include "ui_idd_menuitem.h"
#include "ui_idd_menupage.h"
#include "ui_idd_packagebox.h"
#include "ui_idd_setbox.h"
#include "ui_idd_supportpage.h"
#include "ui_idd_vtypebox.h"

#endif
