PRJ = LavaPE_UI

MOCABLES=LavaPEMainFrameBase.h

EXEC = LavaPE_UI.so
SUBPRO=disco wxqDocView LavaBase

CPP_INCLUDES = -I. -I../disco -I../LavaBase -I../LavaBase/Generated -I../wxqDocView -IGenerated -I$(QTDIR)/include

CPP_FLAGS =

include ../common.mk

