PRJ = LavaPE_UI

MOCABLES=

EXEC = LavaPE_UI.so
SUBPRO=disco wxqDocView LavaBase

CPP_INCLUDES = -I. -I../disco -I../LavaBase -I../LavaBase/Generated -I../wxqDocView -IGenerated -I$(QTDIR)/include

CPP_FLAGS = -DQT3_SUPPORT

include ../common.mk

