PRJ = LavaPE_UI

MOCABLES=

EXEC = LavaPE_UI.so
SUBPRO=SFLsockets disco wxqDocView LavaBase

CPP_INCLUDES = -I. -I../disco -I../SFLsockets -I../LavaBase -I../LavaBase/Generated -I../wxqDocView -IGenerated -I$(QTDIR)/include

include ../common.mk

