PRJ = Lava

MOCABLES=Lava.h LavaDoc.h MainFrm.h

EXEC = Lava

QRC = ../Lava_resources.qrc

SUBPRO=disco wxqDocView LavaBase LavaGUI Lava_UI Interpreter LavaStream

CPP_INCLUDES = -I. -Ires -I../LavaBase/Generated \
	-I../Interpreter -I../Lava_UI -I../Lava_UI/Generated -I../LavaGUI \
	-I../wxqDocView -I../disco -I../LavaBase

CPP_FLAGS = -DINTERPRETER -DNEEDS_INT_DEFINED


include ../common.mk
