MOCABLES=AboutBox.h LavaAppBase.h LavaBaseDoc.h PEBaseDoc.h DumpView.h

EXEC = LavaBase.so
SUBPRO=disco wxqDocView

CPP_INCLUDES = -I. -IGenerated -I../disco -I../wxqDocView -I$(QTDIR)/include

include ../common.mk

