PRJ = LavaBase

MOCABLES=AboutBox.h LavaAppBase.h LavaBaseDoc.h PEBaseDoc.h DumpView.h

EXEC = LavaBase.so
SUBPRO=disco wxqDocView SFLsockets

CPP_INCLUDES = -I. -IGenerated -I../disco -I../wxqDocView -I../SFLsockets -I$(QTDIR)/include
CPP_FLAGS = -DNEEDS_INT_DEFINED

include ../common.mk

