PRJ = LavaBase

MOCABLES=AboutBox.h LavaAppBase.h LavaBaseDoc.h PEBaseDoc.h DumpView.h LavaThread.h

DLL = LAVABASE
EXEC = LavaBase.so
SUBPRO=disco wxqDocView

CPP_INCLUDES = -I. -IGenerated -I../disco -I../wxqDocView

CPP_FLAGS = -DNEEDS_INT_DEFINED -DLAVABASE_EXPORT

include ../common.mk

