//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by LavaExecs.rc
//
#define IDR_CONSTR_TOOLS                2112
#define IDR_OP_TOOLBAR                  2114
#define IDR_EXEC_SWITCHES               2115
#define IDD_COMMENT                     2128
#define IDB_BITMAPEnums                 2134
#define IDR_ACCELERATOR1                2143
#define IDD_DIALOG3                     2144
#define IDD_DIALOG4                     2145
#define IDB_BITMAPNewCFunc              2146
#define IDB_BITMAPNewPFunc              2147
#define IDC_EDIT_COMMENT                5000
#define IDC_INLINE                      5001
#define IDC_TRAILING                    5002
#define IDC_STATICPRINTTEXT             5007
#define IDC_ComboSubObjects             5008
#define IDC_StaticSubObjects            5009
#define IDC_StaticBasics                5011
#define IDC_ComboStatFuncs              5012
#define IDC_ComboClassFuncs             5013
#define IDC_ComboTypes                  5014
#define IDC_ComboObjects                5015
#define IDC_ComboFuncs                  5016
#define IDC_StaticTypes                 5017
#define IDC_StaticObjects               5018
#define IDC_StaticFuncs                 5019
#define IDC_ComboSNew                   5020
#define IDC_ComboNew                    5021
#define IDC_ComboEnums                  5022
#define IDC_ButtonEnum                  5023
#define IDC_ComboSetObjects             5024
#define IDC_ComboCompObjects            5025
#define IDC_ComboUpcasts                5026
#define IDC_ComboBasicUpcasts           5027
#define IDC_ComboSetTypes               5028
#define IDC_ComboAttach                 5029
#define IDC_CompoInterf                 5030
#define IDC_COMBOCall                   5032
#define IDC_ComboBaseInis               5033
#define IDC_COMBO1                      5034
#define IDC_COMBOCallback               5034
#define IDC_CompaTypes                  5036
#define IDC_CompaBTypes                 5037
#define IDC_NewFunc                     5038
#define IDC_NewPFunc                    5039
#define ID_C_INSERT                     42022
#define ID_ENTER_CONST                  42023
#define ID_SWITCH                       42024
#define ID_INNER                        42025
#define ID_ENTER_VARNAME                42026
#define ID_IF                           42027
#define ID_FOREACH                      42028
#define ID_DECLARE                      42029
#define ID_ERROR                        42030
#define ID_F1_HELP                      42030
#define ID_TOGGLE_CATEGORY              42031
#define ID_COPY                         42032
#define ID_IF_EXPR                      42033
#define ID_LT                           42034
#define ID_GE                           42035
#define ID_EQ                           42036
#define ID_NE                           42037
#define ID_GT                           42039
#define ID_SELECT                       42041
#define ID_PLUS                         42043
#define ID_MULT                         42045
#define ID_BIT_OR                       42047
#define ID_LE                           42048
#define ID_AND                          42050
#define ID_BIT_XOR                      42056
#define ID_BIT_AND                      42064
#define ID_LSHIFT                       42068
#define ID_RSHIFT                       42069
#define ID_IN                           42071
#define ID_OR                           42075
#define ID_REPLACE                      42076
#define ID_DEFERRED                     42077
#define ID_OPT_CLAUSE                   42077
#define ID_XOR                          42078
#define ID_OR_ELSE                      42088
#define ID_TRUE                         42091
#define ID_FALSE                        42092
#define ID_NULL                         42093
#define ID_CLASS_CALL                   42101
#define ID_FUNC_STM                     42102
#define ID_INVERT                       42103
#define ID_DOUBLE                       42104
#define ID_DIVIDE                       42108
#define ID_NOT                          42109
#define ID_CONST                        42112
#define ID_INSERT_AFTER                 42113
#define ID_INSERT_BEFORE                42114
#define ID_NO_COMMENTS                  42119
#define ID_THROW                        42120
#define ID_UNREGISTER                   42121
#define ID_PLUS_MINUS                   42122
#define ID_TOGGLE_ARROWS                42123
#define ID_NEW_LINE                     42125
#define ID_REGISTER                     42126
#define ID_MY_ITF                       42127
#define ID_MODULUS                      42128
#define ID_IGNORE                       42129
#define ID_ATTACH                       42132
#define ID_YIELD                        42133
#define ID_STATIC_CALL                  42134
#define ID_VFUNC_CALL                   42135
#define ID_ASSIGN                       42136
#define ID_FUNC_CALL_OBJ                42137
#define ID_TYPE_SWITCH                  42138
#define ID_INTERVAL                     42139
#define ID_EDIT_COMMENT                 42140
#define ID_UUID                         42141
#define ID_ATOMIC                       42142
#define ID_CALL                         42143
#define ID_EXISTS                       42144
#define ID_CREATE                       42145
#define ID_QUERY_ITF                    42146
#define ID_SET_AT                       42147
#define ID_GET_AT                       42148
#define ID_AND_THEN                     42149
#define ID_SHOW_COMMENTS                42150
#define ID_CONCURRENT                   42151
#define ID_ASSERT                       42152
#define ID_CONFLICT                     42153
#define ID_INSERT_STM                   42155
#define ID_TOGGLE                       42156
#define ID_REFRESH                      42157
#define ID_REPLACE_EXP                  42158
#define ID_CLONE                        42159
#define ID_EVALUATE                     42160
#define ID_INPUT_ARROW                  42161
#define ID_TOGGLE_FCOMP                 42166
#define ID_HANDLE                       42167
#define ID_STATIC_FUNC                  42168
#define ID_OPT_LOCAL_VAR                42170
#define ID_ITEM                         42171
#define ID_QUA                          42172
#define ID_FAIL                         42175
#define ID_SUCCEED                      42176
#define ID_ORD                          42177
#define ID_OR_EXCEPTION                 42178

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2150
#define _APS_NEXT_COMMAND_VALUE         42179
#define _APS_NEXT_CONTROL_VALUE         5040
#define _APS_NEXT_SYMED_VALUE           6000
#endif
#endif
