PRJ = LavaExecs

MOCABLES = ComboBar.h ExecView.h

EXEC = LavaExecs.so
SUBPRO=disco wxqDocView LavaBase LavaPE_UI SFLsockets

CPP_INCLUDES = -Ires/TOOLBUTTONS -I../LavaPE_UI -I../LavaPE_UI/Generated -I../LavaPE/res/TreeIcons -I../LavaPE/res -I../LavaPE/res/TOOLBUTTONS -I../LavaPE -I. -IGenerated -I../LavaBase/Generated -I../wxqDocView -I../disco -I../SFLsockets -I../LavaBase -I../Lava -I$(QTDIR)/include

include ../common.mk

