PRJ = LavaExecs

MOCABLES = ComboBar.h ExecView.h

EXEC = LavaExecs.so
SUBPRO=disco wxqDocView LavaBase LavaPE_UI

CPP_INCLUDES = -Ires/TOOLBUTTONS -I../LavaPE_UI -I../LavaPE_UI/Generated -I../LavaPE/res/TreeIcons -I../LavaPE/res -I../LavaPE/res/TOOLBUTTONS -I../LavaPE -I. -IGenerated -I../LavaBase/Generated -I../wxqDocView -I../disco -I../LavaBase -I../Lava -I$(QTDIR)/include -I../Lava -I$(QTDIR)/include/Qt -I$(QTDIR)/include/QtCore -I../Lava -I$(QTDIR)/include/QtGui -I../Lava -I$(QTDIR)/include/Qt3Support

CPP_FLAGS = -DEXECVIEW

include ../common.mk

