#!/bin/sh -v
if test $1 == $2 ; then
  exit
fi
cd $1
if test -d $2/LavaIcons ; then
  rm -rf $2/LavaIcons
fi
cp -r -f -p $1/LavaIcons $2
if test -d $2/std; then
  rm -rf $2/std
fi
cp -r -p $1/std $2
cp -f $1/std_m.htm $2
cp -f $1/std.htm $2
cp -f $1/std_1.htm $2



