#!/bin/sh
if test $1 == $2 ; then
  exit
fi
cd $1
if test -d $2/LavaIcons ; then
  rm -rf $2/LavaIcons
fi
cp -r -f -p LavaIcons $2
if test -d $2/std; then
  rm -rf $2/std
fi
cp -r -p std $2
cp -f std_m.htm $2
cp -f std.htm $2
cp -f std_1.htm $2



