PRJ = wxqDocView

MOCABLES = docview.h mdiframes.h

EXEC = wxqDocView.so
SUBPRO=SFLsockets disco

CPP_INCLUDES = -I../disco -I../SFLsockets -I. -I$(QTDIR)/include

CPP_FLAGS = __UNIX__

include ../common.mk

