PRJ = wxqDocView

MOCABLES = docview.h mdiframes.h

EXEC = wxqDocView.so
SUBPRO=disco

CPP_INCLUDES = -I../disco -I. -I$(QTDIR)/include -I$(QTDIR)/include/Qt -I$(QTDIR)/include/QtCore -I$(QTDIR)/include/QtGui -I$(QTDIR)/include/Qt3Support

CPP_FLAGS = -DWXMAKINGDLL

include ../common.mk

