MOCABLES = FormWid.h LavaGUIFrame.h LavaGUIPopup.h LavaGUIView.h LavaMenu.h TButton.h TComboBox.h TEdit.h TStatic.h

EXEC = LavaGUI.so
SUBPRO=disco wxqDocView LavaBase

CPP_INCLUDES = -I../LavaPE_UI -I../LavaPE/res/TreeIcons -I../LavaPE/res -I../LavaPE/res/TOOLBUTTONS -I../LavaPE -I. -I../LavaBase/Generated -IGenerated -I../wxqDocView -I../disco -I../LavaBase -I../Lava -I$(QTDIR)/include

include ../common.mk

