PRJ = LavaGUI

MOCABLES = CmdExec.h FormWid.h LavaGUIFrame.h LavaGUIPopup.h LavaGUIView.h LavaMenu.h TButton.h TComboBox.h TEdit.h TStatic.h

EXEC = LavaGUI.so
SUBPRO=disco wxqDocView LavaBase

CPP_INCLUDES =  -I../disco -I../LavaPE/res/TreeIcons -I../LavaPE/res -I../LavaPE/res/TOOLBUTTONS -I. -I../LavaBase/Generated -IGenerated -I../wxqDocView -I../LavaBase -I../Lava

CPP_FLAGS = -DLAVAGUI_EXPORT -DNEEDS_INT_DEFINED

include ../common.mk
