PRJ = LavaGUI

MOCABLES = FormWid.h LavaGUIFrame.h LavaGUIPopup.h LavaGUIView.h LavaMenu.h TButton.h TComboBox.h TEdit.h TStatic.h

EXEC = LavaGUI.so
SUBPRO=disco wxqDocView LavaBase SFLsockets

CPP_INCLUDES = -I../LavaPE/res/TreeIcons -I../LavaPE/res -I../LavaPE/res/TOOLBUTTONS -I. -I../LavaBase/Generated -IGenerated -I../wxqDocView -I../disco -I../SFLsockets -I../LavaBase -I../Lava -I$(QTDIR)/include

CPP_FLAGS = -DNEEDS_INT_DEFINED

include ../common.mk

