#!/usr/bin/env bash
#
LAVADIST=$(pwd)/$(dirname $0)
LAVADIR=$LAVADIST/lavadir
#echo LAVADIR=$LAVADIR

cd $LAVADIST
ln -s -f lavadir/bin/LavaPE .
ln -s -f lavadir/bin/Lava .
ln -s -f lavadir/samples .

cd $LAVADIR/lib
for library in $(ls lib*) ;
do
#echo lib1=$library, cwd=$(pwd);
if [ $(uname) == Darwin ]; then
install_name_tool -change /usr/local/Trolltech/Qt-4.3.4/QtAssistant.framework/Versions/4/QtAssistant \
@executable_path/../lib/QtAssistant \
-change /usr/local/Trolltech/Qt-4.3.4/QtCore.framework/Versions/4/QtCore @executable_path/../lib/QtCore \
-change /usr/local/Trolltech/Qt-4.3.4/QtGui.framework/Versions/4/QtGui @executable_path/../lib/QtGui \
-change /usr/local/Trolltech/Qt-4.3.4/QtNetwork.framework/Versions/4/QtNetwork @executable_path/../lib/QtNetwork \
-change /usr/local/Trolltech/Qt-4.3.4/QtXml.framework/Versions/4/QtXml @executable_path/../lib/QtXml \
$library
elif [ $(echo $library | colrm 6) != libQt ]; then
$LAVADIR/bin/chrpath -r $LAVADIR/lib $library >/dev/null
fi;
done

cd $LAVADIR/bin
if [ $(uname) == Darwin ]; then
install_name_tool -change /usr/local/Trolltech/Qt-4.3.4/QtAssistant.framework/Versions/4/QtAssistant \
@executable_path/../lib/QtAssistant \
-change /usr/local/Trolltech/Qt-4.3.4/QtCore.framework/Versions/4/QtCore @executable_path/../lib/QtCore \
-change /usr/local/Trolltech/Qt-4.3.4/QtGui.framework/Versions/4/QtGui @executable_path/../lib/QtGui \
-change /usr/local/Trolltech/Qt-4.3.4/QtNetwork.framework/Versions/4/QtNetwork @executable_path/../lib/QtNetwork \
-change /usr/local/Trolltech/Qt-4.3.4/QtXml.framework/Versions/4/QtXml @executable_path/../lib/QtXml \
Lava
else
$LAVADIR/bin/chrpath -r $LAVADIR/lib Lava >/dev/null
fi

if [ $(uname) == Darwin ]; then
install_name_tool -change /usr/local/Trolltech/Qt-4.3.4/QtAssistant.framework/Versions/4/QtAssistant \
@executable_path/../lib/QtAssistant \
-change /usr/local/Trolltech/Qt-4.3.4/QtCore.framework/Versions/4/QtCore @executable_path/../lib/QtCore \
-change /usr/local/Trolltech/Qt-4.3.4/QtGui.framework/Versions/4/QtGui @executable_path/../lib/QtGui \
-change /usr/local/Trolltech/Qt-4.3.4/QtNetwork.framework/Versions/4/QtNetwork @executable_path/../lib/QtNetwork \
-change /usr/local/Trolltech/Qt-4.3.4/QtXml.framework/Versions/4/QtXml @executable_path/../lib/QtXml \
LavaPE
else
$LAVADIR/bin/chrpath -r $LAVADIR/lib LavaPE >/dev/null
fi

if [ $(uname) == Darwin ]; then
cd assistant.app/Contents/MacOS
install_name_tool -change /usr/local/Trolltech/Qt-4.3.4/QtAssistant.framework/Versions/4/QtAssistant \
@executable_path/../lib/QtAssistant \
-change /usr/local/Trolltech/Qt-4.3.4/QtCore.framework/Versions/4/QtCore @executable_path/../lib/QtCore \
-change /usr/local/Trolltech/Qt-4.3.4/QtGui.framework/Versions/4/QtGui @executable_path/../lib/QtGui \
-change /usr/local/Trolltech/Qt-4.3.4/QtNetwork.framework/Versions/4/QtNetwork @executable_path/../lib/QtNetwork \
-change /usr/local/Trolltech/Qt-4.3.4/QtXml.framework/Versions/4/QtXml @executable_path/../lib/QtXml \
assistant
else
;
#$LAVADIR/bin/chrpath -r $LAVADIR/lib assistant
fi
