#!/usr/bin/env bash
#
LAVADIST=$(dirname $0)
LAVADIR=$LAVADIST/lavadir

cd $LAVADIST
ln -s -f lavadir/bin/LavaPE .
ln -s -f lavadir/bin/Lava .
ln -s -f lavadir/samples .

cd $LAVADIR/lib
for library in $(ls);
do
if [ $(uname) == Darwin ]; then
install_name_tool -change /usr/local/Trolltech/Qt-4.3.4/QtAssistant.framework/Versions/4/QtAssistant @executable_path/../lib/QtAssistant \
-change /usr/local/Trolltech/Qt-4.3.4/QtCore.framework/Versions/4/QtCore @executable_path/../lib/QtCore \
-change /usr/local/Trolltech/Qt-4.3.4/QtGui.framework/Versions/4/QtGui @executable_path/../lib/QtGui \
-change /usr/local/Trolltech/Qt-4.3.4/QtNetwork.framework/Versions/4/QtNetwork @executable_path/../lib/QtNetwork \
-change /usr/local/Trolltech/Qt-4.3.4/QtXml.framework/Versions/4/QtXml @executable_path/../lib/QtXml \
$library
else
../bin/chrpath -r $LAVADIR/lib $library
done

cd $LAVADIR/bin
if [ $(uname) == Darwin ]; then
install_name_tool -change /usr/local/Trolltech/Qt-4.3.4/QtAssistant.framework/Versions/4/QtAssistant @executable_path/../lib/QtAssistant \
-change /usr/local/Trolltech/Qt-4.3.4/QtCore.framework/Versions/4/QtCore @executable_path/../lib/QtCore \
-change /usr/local/Trolltech/Qt-4.3.4/QtGui.framework/Versions/4/QtGui @executable_path/../lib/QtGui \
-change /usr/local/Trolltech/Qt-4.3.4/QtNetwork.framework/Versions/4/QtNetwork @executable_path/../lib/QtNetwork \
-change /usr/local/Trolltech/Qt-4.3.4/QtXml.framework/Versions/4/QtXml @executable_path/../lib/QtXml \
Lava
else
../bin/chrpath -r $LAVADIR/lib Lava
done

if [ $(uname) == Darwin ]; then
install_name_tool -change /usr/local/Trolltech/Qt-4.3.4/QtAssistant.framework/Versions/4/QtAssistant @executable_path/../lib/QtAssistant \
-change /usr/local/Trolltech/Qt-4.3.4/QtCore.framework/Versions/4/QtCore @executable_path/../lib/QtCore \
-change /usr/local/Trolltech/Qt-4.3.4/QtGui.framework/Versions/4/QtGui @executable_path/../lib/QtGui \
-change /usr/local/Trolltech/Qt-4.3.4/QtNetwork.framework/Versions/4/QtNetwork @executable_path/../lib/QtNetwork \
-change /usr/local/Trolltech/Qt-4.3.4/QtXml.framework/Versions/4/QtXml @executable_path/../lib/QtXml \
LavaPE
else
../bin/chrpath -r $LAVADIR/lib LavaPE
done

if [ $(uname) == Darwin ]; then
cd assistant.app/Contents/MacOS
install_name_tool -change /usr/local/Trolltech/Qt-4.3.4/QtAssistant.framework/Versions/4/QtAssistant @executable_path/../lib/QtAssistant \
-change /usr/local/Trolltech/Qt-4.3.4/QtCore.framework/Versions/4/QtCore @executable_path/../lib/QtCore \
-change /usr/local/Trolltech/Qt-4.3.4/QtGui.framework/Versions/4/QtGui @executable_path/../lib/QtGui \
-change /usr/local/Trolltech/Qt-4.3.4/QtNetwork.framework/Versions/4/QtNetwork @executable_path/../lib/QtNetwork \
-change /usr/local/Trolltech/Qt-4.3.4/QtXml.framework/Versions/4/QtXml @executable_path/../lib/QtXml \
assistant;
else
../bin/chrpath -r $LAVADIR/lib assistant
done
