#!/bin/sh
#
rm -f lavape lava
echo "#!/bin/bash">lavape
LAVADIR=`pwd`
echo "export LAVADIR=$LAVADIR">>lavape
echo "export LD_LIBRARY_PATH=$LAVADIR/lib:/usr/lib:/lib">>lavape
echo "cd $LAVADIR/bin">>lavape
echo "./LavaPE">>lavape
chmod a+x lavape

echo "export LAVADIR=$LAVADIR">>lava
echo "export LD_LIBRARY_PATH=$LAVADIR/lib:/usr/lib:/lib">>lava
echo "cd $LAVADIR/bin">>lava
echo "./Lava">>lava
chmod a+x lava
