MOCABLES=

EXEC = Interpreter.so
SUBPRO=disco wxqDocView LavaBase

CPP_INCLUDES = -I. -I../LavaBase -I../LavaExecs -I../disco -I../wxqDocView -I$(QTDIR)/include
CPP_FLAGS = -DINTERPRETER

include ../common.mk

DLL = LAVAEXECS
		
