#ifndef _disco_PCH
#define _disco_PCH

#include "qaction.h"
#include "qapplication.h"
#include "qhash.h"
#include "QtAssistant/qassistantclient.h"
#include "qpushbutton.h"
#include "qgroupbox.h"
#include "qcheckbox.h"
#include "qclipboard.h"
#include "qcolor.h"
#include "qcolordialog.h"
#include "qcombobox.h"
#include "qcursor.h"
#include "qdatastream.h"
#include "qdesktopwidget.h"
#include "qdialog.h"
#include "qdir.h"
#include "qevent.h"
#include "qfile.h"
#include "qfiledialog.h"
#include "qfileinfo.h"
#include "qfont.h"
#include "qfontdialog.h"
#include "qfontmetrics.h"
#include "qframe.h"
#include "qglobal.h"
#include "qicon.h"
#include "qinputdialog.h"
#include "qlabel.h"
#include "qlayout.h"
#include "qlibrary.h"
#include "qlineedit.h"
#include "qmainwindow.h"
#include "qmap.h"
#include "qmenubar.h"
#include "qmenudata.h"
#include "qmetaobject.h"
#include "qmessagebox.h"
#include "qnamespace.h"
#include "qobject.h"
#include "qpainter.h"
#include "qpalette.h"
#include "qpixmap.h"
#include "qpixmapcache.h"
#include "qmenu.h"
#include "qprocess.h"
#include "qpushbutton.h"
#include "qrect.h"
#include "qsignalmapper.h"
#include "qradiobutton.h"
#include "qscrollarea.h"
#include "qsettings.h"
#include "qsize.h"
#include "qsizepolicy.h"
#include "qspinbox.h"
#include "qsplitter.h"
#include "qstatusbar.h"
#include "qstylefactory.h"
#include "qstring.h"
#include "qstringlist.h"
#include "qstringlist.h"
#include "qstyle.h"
#include "qtabbar.h"
#include "qtabwidget.h"
#include "qtextedit.h"
#include "qthread.h"
#include "qtimer.h"
#include "qtoolbar.h"
#include "qtoolbutton.h"
#include "qtooltip.h"
#include "qtranslator.h"
#include "qvalidator.h"
#include "qwhatsthis.h"
#include "qwidget.h"
#include "qworkspace.h"

#include <QByteArray>
#include <QComboBox>
#include <QHBoxLayout>
#include <QFocusEvent>
#include <QMenu>
#include <QWhatsThis>
#include <QMouseEvent>
#include <QResizeEvent>
#include <QCloseEvent>
#include <QVBoxLayout>
#include <QTextEdit>
#include <QTextStream>
#include <QTreeWidget>
#include <QHeaderView>
#include <QAbstractEventDispatcher>
#include "qfiledialog.h"
#include <QItemDelegate>
#include <QScrollBar>
#include <QTextCursor>
#include <QSignalMapper>
#include <QAbstractSocket>
#include <QSemaphore>
#include <QMutex>
#include <QtDebug>
#include <QtTest/QtTest>
#include <QSortFilterProxyModel>

#include "SYSTEM.h"

#include <string.h>
//#include <stdlib.h>
#include <time.h>
#include <ctype.h>
#include <signal.h>
#include <sys/stat.h>

#include "AnyType.h"
#include "ASN1File.h"
#include "ASN1.h"
#include "ASN1pp.h"
#include "CDPpp.h"
#include "ChainA.h"
#include "CHAINANY.h"
#include "ChString.h"
#include "Convert.h"
#include "DateTime.h"
#include "DIO.h"
#include "DString.h"
#include "Halt.h"
#include "InFile.h"
#include "MachDep.h"
#include "MACROS.h"
#include "NestA.h"
#include "NESTANY.h"
#include "OutFile.h"
#include "PMDump.h"
#include "SETpp.h"
#include "STR.h"
#include "TextFile.h"
#include "UNIX.h"
#include "wx_obj.h"

#endif
