PRJ = Lava_UI

MOCABLES=

EXEC = Lava_UI.so
SUBPRO=SFLsockets disco wxqDocView LavaBase

CPP_INCLUDES = -I. -IGenerated -I../disco -I../wxqDocView -I$(QTDIR)/include

CPP_FLAGS = -DQT3_SUPPORT

include ../common.mk

