PRJ = Lava_UI

MOCABLES=LavaMainFrameBase.h

EXEC = Lava_UI.so
SUBPRO=disco wxqDocView LavaBase

CPP_INCLUDES = -I. -IGenerated -I../disco -I../wxqDocView

CPP_FLAGS = -DLAVAUI_EXPORT

include ../common.mk
