PRJ = Lava_UI

MOCABLES=LavaMainFrameBase.h

EXEC = Lava_UI.so
SUBPRO=disco wxqDocView LavaBase

CPP_INCLUDES = -I. -IGenerated -I../disco -I../wxqDocView -I../LavaBase -I../LavaBase/Generated

CPP_FLAGS = -DLAVAUI_EXPORT -DNEEDS_INT_DEFINED

include ../common.mk
